using Autodesk.Revit.UI;
using ClashResolveAI.Core;
using ClashResolveAI.LiveMonitor;
using ClashResolveAI.Services;
using ClashResolveAI.Inspection;
using System.Windows.Threading;

int passed=0;
void Check(bool condition,string message){if(!condition)throw new Exception(message);passed++;Console.WriteLine("PASS "+message);}
var owner=new LiveMonitorService();var app=new UIApplication();
using var gateway=new RevitLiveMonitorGateway(owner);
gateway.Activate("A");long a=gateway.Generation("A");
ExternalEvent.Raises=0;
gateway.Submit(LiveOperation.Refresh);gateway.Submit(LiveOperation.Refresh);
Check(ExternalEvent.Raises==1 && gateway.QueueDepth==1,"One outstanding wake and one coalesced refresh");
gateway.Execute(app);
Check(owner.Calls.SequenceEqual(new[]{"refresh:A"}),"Valid refresh dispatches once to its captured project");
gateway.Submit(LiveOperation.Clear);app.ActiveUIDocument!.Document.Key="B";gateway.Execute(app);
Check(!owner.Calls.Contains("clear:B") && gateway.StaleRequestCount==1,"Delayed clear cannot clear the newly active project");
app.ActiveUIDocument.Document.Key="A";
gateway.Submit(LiveOperation.Cancel);gateway.Activate("B");gateway.Activate("A");gateway.Execute(app);
Check(!owner.Calls.Contains("cancel:A") && !gateway.IsCurrent("A",a),"Switching away and back rejects old queued controls");
owner.Calls.Clear();gateway.Submit(LiveOperation.Clear);gateway.Submit(LiveOperation.Refresh);gateway.Execute(app);
Check(owner.Calls.Contains("clear:A") && !owner.Calls.Contains("refresh:A"),"Clear renews generation and rejects pre-clear queued work");
gateway.Submit(LiveOperation.Refresh);app.ActiveUIDocument.Document.IsValidObject=false;gateway.Execute(app);
Check(!owner.Calls.Contains("refresh:A"),"Invalid native document rejects API work");
app.ActiveUIDocument.Document.IsValidObject=true;
gateway.Submit(LiveOperation.Refresh);gateway.Close("A");gateway.Execute(app);
Check(gateway.QueueDepth==0 && owner.Calls.Contains("close:A"),"Confirmed closure removes queued work and session state");
gateway.Activate("A");
gateway.Submit(LiveOperation.Selection);app.ActiveUIDocument.Document.IsFamilyDocument=true;gateway.Execute(app);
Check(!owner.Calls.Contains("selection"),"Family documents reject live API requests");
app.ActiveUIDocument.Document.IsFamilyDocument=false;
var clash=new LiveClashDto {SessionGeneration=gateway.Generation("A")};RadarDataStore.Instance.Rows.Add(clash);
gateway.Submit(LiveOperation.Navigate3D,"pair",3);gateway.Execute(app);
Check(ClashViewNavigation.Calls==1 && ClashViewNavigation.DeferredValid!(),"Current clash navigation carries a completion guard");
gateway.Renew("A");
Check(!ClashViewNavigation.DeferredValid!(),"Session reset invalidates deferred navigation completion");
clash.SessionGeneration=gateway.Generation("A");gateway.Submit(LiveOperation.Inspect,"pair",2);gateway.Execute(app);
Check(InspectionHandler.Calls==0,"Geometry revision mismatch rejects inspection");
clash.Stale=true;gateway.Submit(LiveOperation.Navigate2D,"pair",3);gateway.Execute(app);
Check(ClashViewNavigation.Calls==1,"Dirty geometry rejects navigation");
clash.Stale=false;
InspectionHandler.BeforePublish=()=>gateway.Renew("A");gateway.Submit(LiveOperation.Inspect,"pair",3);gateway.Execute(app);
Check(InspectionHandler.Calls==1 && ClashRadarPanel.Instance.Inspections==0,"Late inspection publication is rejected after a generation change");
InspectionHandler.BeforePublish=null;
clash.SessionGeneration=gateway.Generation("A");gateway.Submit(LiveOperation.Snapshot,"pair",3);gateway.Execute(app);
Check(ClashSnapshotStore.Instance.Latest?.DocumentKey=="A" && ClashSnapshotStore.Instance.Latest.SessionGeneration==gateway.Generation("A"),"Snapshot publication carries its validated document and generation");
ExternalEvent.Result=ExternalEventRequest.Denied;ExternalEvent.Raises=0;
gateway.Submit(LiveOperation.Refresh);DispatcherTimer.Latest!.Fire();
Check(gateway.QueueDepth==1 && ExternalEvent.Raises==2,"Denied external-event wakes retain work and retry");
ExternalEvent.Result=ExternalEventRequest.Accepted;DispatcherTimer.Latest.Fire();gateway.Execute(app);
Check(owner.Calls.Contains("refresh:A"),"Retried wake eventually dispatches retained work");
owner.HasPendingWork=true;owner.Calls.Clear();DispatcherTimer.Latest.Fire();gateway.Execute(app);
Check(owner.Calls.Contains("advance:A"),"The shared gateway advances live geometry work");
var scene=new InspectionScene {Min=7,Max=9};var preferences=new InspectorPreferences {PaddingFeet=2};
var payload=new RevitLiveMonitorGateway.PinPayload(scene,preferences);scene.Min=100;preferences.PaddingFeet=100;
Check(payload.Scene.Min==7 && payload.Preferences.PaddingFeet==2,"Queued pin freezes UI-owned framing and preferences");
owner.Calls.Clear();gateway.Submit(LiveOperation.Mode,payload:MonitorMode.Trigger);gateway.Execute(app);
Check(owner.Calls.Contains("mode:A:Trigger"),"Mode changes dispatch through the guarded gateway");
owner.Calls.Clear();gateway.Submit(LiveOperation.Mode,payload:MonitorMode.Off);gateway.Activate("B");app.ActiveUIDocument.Document=new Autodesk.Revit.DB.Document {Key="B"};gateway.Execute(app);
Check(!owner.Calls.Any(c=>c.StartsWith("mode:")),"A delayed mode change cannot affect a different active document");
gateway.Dispose();Check(!gateway.Submit(LiveOperation.Refresh) && !DispatcherTimer.Latest.Started,"Disposed gateway rejects submissions and stops its timer");
Console.WriteLine($"{passed} gateway dispatch checks passed.");
