using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using ClashResolveAI;
using ClashResolveAI.Alert;
using ClashResolveAI.Core;
using ClashResolveAI.LiveMonitor;
using Engine=ClashResolveAI.ClashEngine.ClashEngine;

int passed=0;
void Check(bool condition,string message){if(!condition)throw new Exception(message);passed++;Console.WriteLine("PASS "+message);}
var app=new UIApplication();var doc=app.ActiveUIDocument!.Document;
doc.Elements[1]=new Element{Id=new(1),UniqueId="A"};doc.Elements[2]=new Element{Id=new(2),UniqueId="B"};
var radar=RadarDataStore.Instance;radar.Activate(doc.Key);radar.Clear();radar.BeginSession();
var alert=new AlertSystem();using var scheduler=new LiveScanScheduler(app,alert);
LiveMonitorService.Instance.OnRenew=scheduler.SessionRenewed;
void Record(long id,LiveChangeKind kind=LiveChangeKind.Modified,bool global=false){ScanCoordinator.Revisions.Changed(doc.Key,new[]{id},global);scheduler.Record(doc,new[]{new ElementId(id)},kind,global);}
void Pump(){scheduler.Advance(doc.Key,LiveMonitorService.Instance.Generation);}
void Ready(){Thread.Sleep(320);Pump();for(int i=0;i<10&&!Engine.Infinite&&scheduler.Status.Outcome==LiveScanOutcome.Checking;i++){Thread.Sleep(30);Pump();}}
Record(1,LiveChangeKind.Added);Ready();
Check(radar.ActiveCount==1&&scheduler.QueueDepth(doc.Key)==0&&scheduler.Status.Outcome==LiveScanOutcome.Completed,"Scheduler publishes detached DTOs and acknowledges a completed local batch");
var dto=radar.GetActive().Single();var resolved=LiveClashResolver.Resolve(doc,dto);
Check(resolved.ElementA.UniqueId=="A"&&resolved.ElementB.UniqueId=="B","API resolver resolves both endpoint UniqueIds");
bool Reject(Action action){try{action();return false;}catch(InvalidOperationException){return true;}}
doc.Elements[1].VersionGuid=Guid.NewGuid();
Check(Reject(()=>LiveClashResolver.Resolve(doc,dto)),"Endpoint geometry version change rejects an old DTO without relying on numeric IDs");
Record(1);Ready();dto=radar.GetActive().Single();
var old=doc.Elements[1];doc.Elements[1]=new Element{Id=new(1),UniqueId="replacement"};
Check(Reject(()=>LiveClashResolver.Resolve(doc,dto)),"Reused numeric IDs cannot resolve an old endpoint UniqueId");doc.Elements[1]=old;
ClashResolveAI.Rules.RulesEngine.Contents="changed rules";
Check(Reject(()=>LiveClashResolver.Resolve(doc,dto)),"Changed rule contents reject otherwise unchanged endpoint geometry");
Pump();Check(scheduler.Status.RequiresFullScan,"Environment changes produce an explicit Full Scan requirement");
scheduler.RequestCheck(doc,new[]{new ElementId(1)});Ready();
Check(scheduler.Status.RequiresFullScan&&scheduler.QueueDepth(doc.Key)>0,"Manual checks cannot bypass a global completeness pause");
long rev=ScanCoordinator.DocumentRevision(doc.Key);scheduler.FullScanStarted(doc.Key,rev);int jobs=Engine.Jobs;Record(1);Ready();
Check(Engine.Jobs==jobs&&scheduler.QueueDepth(doc.Key)>0,"Full Scan preserves edits and prevents local job creation");
scheduler.FullScanEnded(doc,doc.Key,false,true,null,ScanCoordinator.DocumentRevision(doc.Key));
Check(scheduler.Status.RequiresFullScan&&scheduler.QueueDepth(doc.Key)>0,"Cancelled Full Scan preserves the requirement and queued edits");
rev=ScanCoordinator.DocumentRevision(doc.Key);scheduler.FullScanStarted(doc.Key,rev);var fullScope=new ScanScope(doc.Key);fullScope.Note(1,"","");fullScope.Note(2,"","");
scheduler.FullScanEnded(doc,doc.Key,true,false,fullScope,rev);
Check(scheduler.Status.RequiresFullScan,"A scoped scan cannot clear the global pause");
scheduler.FullScanStarted(doc.Key,rev);int pendingBeforeStaleFull=scheduler.QueueDepth(doc.Key);
scheduler.FullScanEnded(doc,doc.Key,true,true,fullScope,rev+1);
Check(scheduler.Status.RequiresFullScan&&scheduler.QueueDepth(doc.Key)==pendingBeforeStaleFull,"A superseded Full Scan cannot acknowledge queued changes");
scheduler.Clear(doc.Key);Check(scheduler.Status.RequiresFullScan,"Clearing live rows cannot erase a global Full Scan requirement");
scheduler.RequestCheck(doc,new[]{new ElementId(1)});
scheduler.FullScanStarted(doc.Key,rev);scheduler.FullScanEnded(doc,doc.Key,true,true,fullScope,rev);Ready();
Check(!scheduler.Status.RequiresFullScan&&radar.GetActive().Single().SessionGeneration==LiveMonitorService.Instance.Generation,"Successful full coverage advances generation and revalidates live DTOs");
Engine.Infinite=true;Record(1);Ready();Check(scheduler.QueueDepth(doc.Key)>0,"An in-flight sliced scan retains batch ownership");
int beforeDispose=Engine.Disposed;Record(1);Record(2);
Check(Engine.Disposed>beforeDispose&&scheduler.QueueDepth(doc.Key)==2,"Mid-scan edits dispose the old job and preserve later changes including the same ID");
scheduler.Cancel(doc.Key);Engine.Infinite=false;Ready();jobs=Engine.Jobs;
Check(scheduler.Status.Outcome==LiveScanOutcome.Cancelled&&scheduler.QueueDepth(doc.Key)==2,"Cancel preserves pending edits and pauses automatic advancement");
scheduler.RequestCheck(doc,Array.Empty<ElementId>());Ready();Check(Engine.Jobs>jobs&&scheduler.QueueDepth(doc.Key)==0,"Explicit recheck resumes retained changes after cancellation");
Engine.StepDelay=80;AppSettings.Current.LiveMaximumSliceMilliseconds=50;Record(1);Ready();
Check(scheduler.Status.Outcome==LiveScanOutcome.ProtectionPaused&&scheduler.QueueDepth(doc.Key)>0,"An uninterruptible API slice overrun pauses further work and restores its batch");
jobs=Engine.Jobs;Ready();Check(Engine.Jobs==jobs,"Responsiveness protection prevents blind automatic retry");
Engine.StepDelay=0;AppSettings.Current.LiveMaximumSliceMilliseconds=100;scheduler.RequestCheck(doc,new[]{new ElementId(1)});Ready();
Engine.Unreliable=true;Record(1);Ready();
Check(radar.ActiveCount==1&&radar.GetActive().Single().Verification==LiveVerificationState.Unverified&&scheduler.QueueDepth(doc.Key)>0,"Missing geometry retains an unverified clash and unchecked source rather than resolving it");
Engine.Unreliable=false;scheduler.RequestCheck(doc,new[]{new ElementId(1)});Ready();
Engine.Emit=false;Record(1);Ready();
Check(radar.ActiveCount==0&&scheduler.QueueDepth(doc.Key)==0,"Reliable empty local results resolve previous overlaps after movement");
Engine.Emit=true;Record(1);Ready();dto=radar.GetActive().Single();
doc.Elements.Remove(1);Record(1,LiveChangeKind.Deleted);Ready();
Check(radar.ActiveCount==0,"Confirmed host UniqueId deletion resolves its historical clashes");
doc.Elements[1]=old;Record(1,LiveChangeKind.Added);Ready();
Check(radar.ActiveCount==1,"Restoring the same UniqueId after Undo/Redo reactivates the stable pair");
var linked=new Document{Key="linked"};linked.Elements[7]=new Element{Id=new(7),UniqueId="linked-A"};
var link=new RevitLinkInstance{Id=new(9),UniqueId="link-instance",Linked=linked};doc.Elements[9]=link;
var row=new ClashResult{ElementA=doc.Elements[1],ElementB=linked.Elements[7],HostDocumentKey=doc.Key,LinkInstanceB=link.UniqueId,GeometryRevision=ScanCoordinator.DocumentRevision(doc.Key),Origin=ResultOrigin.Live,SessionGeneration=LiveMonitorService.Instance.Generation};
var linkedDto=LiveClashResolver.Capture(doc,row,LiveEnvironment.Capture(doc));
Check(LiveClashResolver.Resolve(doc,linkedDto).ElementB.UniqueId=="linked-A","Loaded-link endpoints resolve inside their specific link instance");
link.Transform.Origin=new XYZ(10,0,0);Check(Reject(()=>LiveClashResolver.Resolve(doc,linkedDto)),"Link transform changes reject old navigation/inspection DTOs");link.Transform.Origin=XYZ.Zero;
link.Linked=null;Check(Reject(()=>LiveClashResolver.Resolve(doc,linkedDto)),"Unloaded links reject stale requests instead of impersonating deletion");link.Linked=linked;
link.Linked=new Document{Key="replacement-linked"};Check(Reject(()=>LiveClashResolver.Resolve(doc,linkedDto)),"Reloading a different linked document invalidates the captured link identity");
link.Linked=linked;
rev=ScanCoordinator.DocumentRevision(doc.Key);scheduler.FullScanStarted(doc.Key,rev);scheduler.FullScanEnded(doc,doc.Key,true,true,fullScope,rev);Ready();
scheduler.SetMode(doc.Key,MonitorMode.Trigger);jobs=Engine.Jobs;Record(1);Ready();
Check(Engine.Jobs==jobs&&scheduler.QueueDepth(doc.Key)==1,"Trigger accumulates changes without automatically creating a scan");
scheduler.RequestCheck(doc,Array.Empty<ElementId>());Ready();
Check(Engine.Jobs>jobs&&scheduler.QueueDepth(doc.Key)==0,"Trigger Check Changes drains its requested work");
jobs=Engine.Jobs;Record(1);Ready();
Check(Engine.Jobs==jobs&&scheduler.QueueDepth(doc.Key)==1,"Changes after a completed Trigger request wait for another click");
scheduler.RequestCheck(doc,Array.Empty<ElementId>());Engine.Infinite=true;Ready();Record(1);Engine.Infinite=false;Ready();
Check(scheduler.QueueDepth(doc.Key)==1&&scheduler.Status.Outcome!=LiveScanOutcome.Checking,"Edits after a Trigger watermark invalidate its batch and wait for a fresh click");
scheduler.SetMode(doc.Key,MonitorMode.Off);jobs=Engine.Jobs;Record(1);scheduler.RequestCheck(doc,new[]{new ElementId(2)});Ready();
Check(scheduler.QueueDepth(doc.Key)==0&&Engine.Jobs==jobs&&!scheduler.NeedsPump(doc.Key),"Off clears pending work and ignores event, check, and timer scan requests");
scheduler.SetMode(doc.Key,MonitorMode.Live);Record(1);Ready();
Check(Engine.Jobs>jobs&&scheduler.QueueDepth(doc.Key)==0,"Returning to Live resumes automatic checking of subsequent changes");
passed+=ViewModelChecks.Run(radar.GetActive().Single());
Console.WriteLine($"{passed} scheduler/resolver/view-model checks passed.");
